easy_admin:
    entities:
          Agenda:
              class: App\Entity\Agenda
              controller:   App\Controller\AgendaController
              label: 'menu.agenda'
              list:
                  title: 'menu.agenda'
                  actions:
                        - {name: 'show', label: '', icon: 'search'}
                        - {name: 'search', label: 'menu.agenda.pesquisar'}
                        - {name: 'edit', label: '', icon: 'pencil'}
                        - {name: 'delete', label: '',icon: 'trash'}

