easy_admin:
    entities:
          Agenda:
              class: App\Entity\Agenda
              controller:   App\Controller\AgendaController
              disabled_actions: ['search', 'delete', 'list']
              label: 'menu.agenda'
              list:
                  title: 'menu.agenda'
                  actions:
                        - {name: 'edit', label: '', icon: 'pencil'}

                  fields:
                         - { property: 'nome',label: 'nome' }
              form:
                  fields:
                         - { property: 'nome',label: 'Evento' }
                         - { property: 'data',label: 'Data Do Evento',type_options: {format: 'dd-MM-yyyy' } }
                         - { property: 'time',label: 'Horário' , type: 'time' }

