easy_admin:
    entities:
          Lancamento:
              class: App\Entity\Lancamento
              controller:   App\Controller\LancamentoController
              label: 'menu.lancamento'
              disabled_actions: ['new', 'edit','delete']
              list:
                  title: 'menu.lancamento'


