easy_admin:
    entities:
          Patrimonio:
              class: App\Entity\Patrimonio
              label: 'menu.patrimonio'
              list:
                  title: 'menu.patrimonio'
                  actions:
                        - {name: 'show', label: '', icon: 'search'}
                        - {name: 'search', label: 'menu.patrimonio.pesquisar'}
                        - {name: 'edit', label: '', icon: 'pencil'}
                        - {name: 'delete', label: '',icon: 'trash'}

