easy_admin:
    entities:
          TipoPagamento:
              class: App\Entity\TipoPagamento
              label: 'menu.pagamento'
              list:
                  title: 'menu.pagamento'
                  actions:
                        - {name: 'show', label: '', icon: 'search'}
                        - {name: 'search', label: 'menu.pagamento.pesquisar'}
                        - {name: 'edit', label: '', icon: 'pencil'}
                        - {name: 'delete', label: '',icon: 'trash'}
                  fields:
                    - { property: 'nome',label: 'nome' }
              form:
                  fields:
                  - { property: 'nome',label: 'nome' }
              show:
                  fields:
                  - { property: 'nome',label: 'nome' }

